<?php

return [
    'PAGINATION_LIMIT' => 20,
    'STATUS_ARR' => ['A'=>'Active','I'=>'Inactive'],
    'PRIORITY_ARR' => ['P'=>'Primary','S'=>'Secondary'],
    'IMAGE_PATH' => base_path()."/public/data",
    'IMAGE_MIME'=>array('jpg', 'jpeg', 'JPG','png','PNG'),
    'PRODUCT_TYPE' => [
        'DRAWING_PRODUCT_TYPE' => 'drawingFiles',
        'MACHINE_MOLD_PRODUCT_TYPE' => 'machineModel',
        'MACHINE_MOLD_ATTACHMENT_PRODUCT_TYPE' => 'machineMoldAttachments',
        'DRAWING_ATTACHMENT_PRODUCT_TYPE' => 'drawingAttachments',
    ],
    'CODE_ID' => [
    	'Screw L/ D Ratio' => 1,
    	'Actuation' => 2,
    	'Actuator 1' => 3,
        'Actuator 2' => 4,
    	'Manufacturing Unit' => 5,
        'Brand' => 6,
        'primary_application' => 7,
        'mother_mold' => 8,
        'blow_mold' => 9,
        'injection_mold' => 10,
        'type_of_packing' => 11,
        'change_over_time' => 1,
    ],
    'HARD_CODED_ID' => [ 
        'MACHINE_GROUP_ID' => 1,
        'MOLD_GROUP_ID' => 2,
        'NECK_GROUP_ID' => 3,
        'PACKING_MATERIAL_GROUP_ID' => 8,
        'CARTON_TYPE_ID' => 13,
    ],
    'CCB' => [
        'Y' =>'Yes',
        'N' => 'No',
    ],
    'PLANNING_STATUS' => [
        'P' => 'Planned',
        'R' => 'Running',
        'C' => 'Closed',
        'SC' => 'Short Closed',
        'CN' => 'Cancelled',
    ],

    'PLANNED_PLANNING_STATUS' => [
        'R' => 'Running',
        'CN' => 'Cancelled',
    ],
    'RUNNING_PLANNING_STATUS' => [
        'C' => 'Closed',
        'SC' => 'Short Closed',
    ],
    'SHORT_CLOSE_PLANNING_STATUS' => [
        'R' => 'Running',
        'CN' => 'Cancelled',
    ],
    'ADMIN_ROLE_ID' => 1,
    'DEFAULT_PERMISSIONS' => [
        'authentication.login' => true,
        'authentication.update_profile' => true,
        'authentication.change_password' => true,
        'shape.add' => true,
        'shape.edit' => true,
        'shape.delete' => true,
        'shape.view' => true,
        'color.add' => true,
        'color.edit' => true,
        'color.delete' => true,
        'color.view' => true,
        'store.add' => true,
        'store.edit' => true,
        'store.delete' => true,
        'store.view' => true,
        'group.add' => true,
        'group.edit' => true,
        'group.view' => true,
        'manufacturer.add' => true,
        'manufacturer.edit' => true,
        'manufacturer.delete' => true,
        'manufacturer.view' => true,
        'type.add' => true,
        'type.edit' => true,
        'type.delete' => true,
        'type.view' => true,
        'necksize.add' => true,
        'necksize.edit' => true,
        'necksize.delete' => true,
        'necksize.view' => true,
        'code_value.add' => true,
        'code_value.edit' => true,
        'code_value.view' => true,
        'user.add' => true,
        'user.edit' => true,
        'user.view' => true,
        'user.reset_password' => true,
        'drawing.add' => true,
        'drawing.edit' => true,
        'drawing.view' => true,
        'drawing.delete' => true,
        'drawing.export' => true,
        'drawing.download_drawing' => true,
        'drawing.download_attachment' => true,
        'mold.add' => true,
        'mold.edit' => true,
        'mold.view' => true,
        'mold.delete' => true,
        'mold.export' => true,
        'machine_model.add' => true,
        'machine_model.edit' => true,
        'machine_model.view' => true,
        'machine_model.delete' => true,
        'machine_model.export' => true,
        'machine.add' => true,
        'machine.edit' => true,
        'machine.view' => true,
        'machine.delete' => true,
        'machine.export' => true,
        'downtime.add' => true,
        'downtime.edit' => true,
        'downtime.view' => true,
        'downtime.delete' => true,
        'downtime.export' => true,
        'defect.add' => true,
        'defect.edit' => true,
        'defect.view' => true,
        'defect.delete' => true,
        'defect.export' => true,
        'product.add' => true,
        'product.edit' => true,
        'product.view' => true,
        'product.delete' => true,
        'product.export' => true,
        'item.add' => true,
        'item.edit' => true,
        'item.view' => true,
        'item.export' => true,
        'planning.add' => true,
        'planning.edit' => true,
        'planning.view' => true,
        'hourly_entry.add' => true,
        'hourly_entry.edit' => true,
        'hourly_entry.view' => true,
        'hourly_entry.delete' => true,
        'daily_entry.add' => true,
        'daily_entry.edit' => true,
        'daily_entry.view' => true,
        'daily_entry.delete' => true,
        'packing_matrix.add' => true,
        'packing_matrix.edit' => true,
        'packing_matrix.view' => true,
        'fg_inward.add' => true,
        'fg_inward.view' => true,
        'rejection.add' => true,
        'rejection.view' => true,
        'rejection.delete' => true,
        'role.view' => true,
        'role.edit' => true,
        'report.daily_production_report' => true,
        'report.management_report' => true,

    ],
    'REJECTION_SOURCE' => [
        'PROD' => 'Production',
        'CUST' => 'Customer Rejection',
    ],
    'username_min_length' => 5,
    'password_min_length' => 6,
    'available_hrs_downtime_reasons' => [3,4],
    'mold_change_over_id' => 4, 
    'preventive_maintenance_id' => 3,   
];
